name: OSX
on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        app: [test]
      fail-fast: false
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'
      - uses: actions/checkout@v2

      - name: Setup AWS vcpkg binary cache
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc-apps/,readwrite" >> $GITHUB_ENV

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git

      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
